# 全局页面配置
global:
  # 相册名称
  album_name: 相册
  # 封面图片路径
  cover_path: /html/album-per/photos/2026-05-01-01.png
  # 相册描述
  album_desc: 分享生活，留住美好！
  # 是否按最新日期在前排序
  new_first: true
  # 本地媒体根路径：完整路径 = local_media_path + id.ext
  local_media_path: /html/album-per/photos/

# 本地媒体列表：日期从 id 中解析
local_media_list:
  - id: 2026-05-01-01
    ext: png
    name: ''
    description: ''
  - id: 2026-05-01-02
    ext: png
    name: ''
    description: ''
  - id: 2026-05-01-03
    ext: png
    name: ''
    description: ''
  - id: 2026-05-01-04
    ext: png
    name: ''
    description: ''

# 远程媒体列表：日期由 date 字段指定，直接使用 url 加载资源
remote_media_list:
- url: https://picsum.photos/1600/900?random=1
  date: 2026-2-16-01
  name: 远程示例图片01
  description: 这是一张远程加载的示例图片
- url: https://picsum.photos/1600/900?random=2
  date: 2026-2-16-02
  name: 远程示例图片02
  description: 这是一张远程加载的示例图片
- url: https://picture.huyongshuang.top/sample_videos/如果不是着急赶路 语文应该是最美的学科了.mp4
  date: 2026-3-1-1
  name: 远程示例视频1
  description: 这是一段远程加载的示例视频
- url: https://picture.huyongshuang.top/sample_videos/济宁好孩子.mp4
  date: 2026-3-1-2
  name: 远程示例视频2
  description: 这是一段远程加载的示例视频
